# Template for Ghostty
background = #0e1514
foreground = #dde4e2
cursor-color = #80d5d1

palette = 0=#2f3635
palette = 1=#ffb4ab
palette = 2=#80d5d1
palette = 3=#b1c8e8
palette = 4=#b0ccca
palette = 5=#006a67
palette = 6=#889392
palette = 7=#dde4e2
